# Generated by Django 5.0.3 on 2024-03-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='message',
            new_name='massage',
        ),
    ]
