# Generated by Django 5.0.3 on 2024-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_alter_news_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.CharField(max_length=500, verbose_name='Главное описание')),
                ('title1', models.CharField(max_length=255, verbose_name='Название 1')),
                ('description1', models.CharField(max_length=255, verbose_name='Описание 1')),
                ('title2', models.CharField(max_length=255, verbose_name='Название 2')),
                ('description2', models.CharField(max_length=255, verbose_name='Описание 2')),
                ('image', models.ImageField(upload_to='portfolio_image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
